[package]
name = "opencl-sys"
version = "0.1.0"
authors = ["Jason Goldberger <jlgoldb2@asu.edu>"]
edition = "2018"
links = "OpenCL"

[dependencies]
libc = "0.2.65"

[build-dependencies]
bindgen = "0.51.1"